--liquibase formatted sql

--changeset ROLE_DEF:01

CREATE TABLE ROLE_DEF (
	ID INTEGER NOT NULL IDENTITY(1,1) PRIMARY KEY, 
	USER_ID varchar(100),
	ROLE_DEF varchar(100)
);

CREATE TABLE USER_DEF (
	ID INTEGER NOT NULL IDENTITY(1,1) PRIMARY KEY, 
	EMAIL_ID varchar(100),
	USER_NAME varchar(100),
	PASSWORD varchar(100)
);

CREATE TABLE IDEA (
	ID INTEGER NOT NULL IDENTITY(1,1) PRIMARY KEY, 
	IDEA_NAME varchar(100),
	CREATED_BY varchar(100)
);

